[package]
name = "rsplug"
version = "0.1.0"
edition = "2024"
description = "Vim plugin manager written in Rust"

[dependencies]
clap = { version = "4.5.48", features = ["derive", "env"] }
colored = "3.0.0"
git2 = "0.20.2"
hashbrown = "0.16.0"
ignore = "0.4.23"
indicatif = { version = "0.18.0", features = ["tokio"] }
itertools = "0.14.0"
once_cell = "1.21.3"
regex = "1.11.3"
sailfish = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.15.0", features = ["default", "hashbrown_0_16"] }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
wildmatch = "2.5.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
