[package]
name = "rsplug"
version = "0.1.0"
edition = "2024"
description = "Vim plugin manager written in Rust"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
colored = "3.0.0"
hashbrown = "0.15.5"
ignore = "0.4.23"
itertools = "0.14.0"
once_cell = "1.21.3"
regex = "1.11.2"
sailfish = "0.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = { version = "3.14.0", features = ["default", "hashbrown_0_15"]}
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
