[workspace]
members = [".", "dag"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/gw31415/rsplug.nvim"

[workspace.dependencies]
hashbrown = "0.16"
thiserror = "2.0"

[package]
name = "rsplug"
version.workspace = true
edition.workspace = true
repository.workspace = true
description = "A blazingly fast Neovim plugin manager written in Rust"
license = "Apache-2.0"

[dependencies]
hashbrown.workspace = true
thiserror.workspace = true

clap = { version = "4.5", features = ["derive", "env"] }
console = "0.16.2"
dag = { path = "dag", features = ["hashbrown"] }
git2 = "0.20"
ignore = "0.4"
indicatif = { version = "0.18", features = ["tokio"] }
itertools = "0.14"
once_cell = "1.21"
regex = "1.12"
sailfish = "0.10"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = { version = "3.16", features = [
	"macros",
	"hashbrown_0_16",
], default-features = false }
tokio = { version = "1.49", features = ["full"] }
toml = "0.9"
unicode-width = "0.2"
wildmatch = "2.6"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
