[workspace]
members = [".", "dag"]
resolver = "3"
package = { version = "0.1.0", edition = "2024" }

[workspace.dependencies]
hashbrown = "0.16.0"
thiserror = "2.0.17"

[package]
name = "rsplug"
version.workspace = true
edition.workspace = true
description = "Vim plugin manager written in Rust"

[dependencies]
hashbrown.workspace = true
thiserror.workspace = true

clap = { version = "4.5.51", features = ["derive", "env"] }
console = "0.16.1"
dag = { path = "dag", features = ["hashbrown"] }
git2 = "0.20.2"
ignore = "0.4.24"
indicatif = { version = "0.18.2", features = ["tokio"] }
itertools = "0.14.0"
once_cell = "1.21.3"
regex = "1.12.2"
sailfish = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.15.1", features = [
	"macros",
	"hashbrown_0_16",
], default-features = false }
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
unicode-width = "0.2.2"
wildmatch = "2.5.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
