[package]
name = "rsplug"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "Vim plugin manager written in Rust"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
hashbrown = "0.15.4"
indicatif = "0.18.0"
itertools = "0.14.0"
log = "0.4.27"
once_cell = "1.21.3"
regex = "1.11.1"
sailfish = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.14.0"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
toml = "0.9.2"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
