[package]
name = "globbench"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.3"
ignore = "0.4.23"
tokio.workspace = true
globwalker = { path = "../globwalker" }
walker = { path = "../walker" }
